export type IPOEntry = {
    name: string;
    ipoPrice: number;
    listingPrice: number;
    gain: number;
  };
  
  // Define the type for the closed IPO data (Record of year -> IPOEntry[])
  export type IPOData = Record<string, IPOEntry[]>;


const closedipoData: IPOData  = {
  "2025": [
    { "name": "Quality Power", "ipoPrice": 425, "listingPrice": 432, "gain": 2 },
    { "name": "Hexaware Technologies", "ipoPrice": 708, "listingPrice": 745, "gain": 5 },
    { "name": "Ajax Engineering", "ipoPrice": 629, "listingPrice": 576, "gain": -8 },
    { "name": "Dr. Agarwal’s Health Care", "ipoPrice": 402, "listingPrice": 402, "gain": 0 },
    { "name": "Denta Water", "ipoPrice": 294, "listingPrice": 330, "gain": 11 },
    { "name": "Stallion India", "ipoPrice": 90, "listingPrice": 120, "gain": 33 },
    { "name": "Laxmi Dental", "ipoPrice": 428, "listingPrice": 542, "gain": 27 },
    { "name": "Quadrant Future Tek", "ipoPrice": 290, "listingPrice": 370, "gain": 29 },
    { "name": "Standard Glass Lining", "ipoPrice": 140, "listingPrice": 176, "gain": 26 },
    { "name": "Indo Farm Equipment", "ipoPrice": 215, "listingPrice": 256, "gain": 19 },
    { "name": "Unimech Aerospace", "ipoPrice": 785, "listingPrice": 1460, "gain": 86 },
    { "name": "Ventive Hospitality", "ipoPrice": 643, "listingPrice": 716, "gain": 11 },
    { "name": "Senores Pharmaceuticals", "ipoPrice": 391, "listingPrice": 594, "gain": 52 },
    { "name": "Carraro India", "ipoPrice": 704, "listingPrice": 660, "gain": -8 },
    { "name": "Concord Enviro Systems", "ipoPrice": 701, "listingPrice": 826, "gain": 18 },
    { "name": "DAM Capital Advisors", "ipoPrice": 283, "listingPrice": 393, "gain": 39 },
    { "name": "Sanathan Textiles", "ipoPrice": 321, "listingPrice": 422, "gain": 31 },
    { "name": "Transrail Lighting", "ipoPrice": 432, "listingPrice": 585, "gain": 36 },
    { "name": "Mamata Machinery", "ipoPrice": 243, "listingPrice": 600, "gain": 147 }
],
"2024": [
    { "name": "Inventurus Knowledge", "ipoPrice": 1329, "listingPrice": 1900, "gain": 43 },
    { "name": "Sai Life Sciences", "ipoPrice": 549, "listingPrice": 650, "gain": 18 },
    { "name": "Mobikwik", "ipoPrice": 279, "listingPrice": 442, "gain": 58 },
    { "name": "Vishal Mega Mart", "ipoPrice": 78, "listingPrice": 104, "gain": 41 },
    { "name": "Suraksha Diagnostic", "ipoPrice": 441, "listingPrice": 438, "gain": -1 },
    { "name": "Enviro Infra", "ipoPrice": 148, "listingPrice": 220, "gain": 49 },
    { "name": "NTPC Green Energy", "ipoPrice": 108, "listingPrice": 111, "gain": 3 },
    { "name": "Zinka Logistics (Blackbuck)", "ipoPrice": 273, "listingPrice": 281, "gain": 3 },
    { "name": "Niva Bupa Health", "ipoPrice": 74, "listingPrice": 78, "gain": 6 },
    { "name": "ACME Solar", "ipoPrice": 289, "listingPrice": 251, "gain": -13 },
    { "name": "Swiggy", "ipoPrice": 390, "listingPrice": 420, "gain": 7 },
    { "name": "Sagility India", "ipoPrice": 30, "listingPrice": 31, "gain": 4 },
    { "name": "Afcons Infrastructure", "ipoPrice": 463, "listingPrice": 426, "gain": -8 },
    { "name": "Waaree Energies", "ipoPrice": 1503, "listingPrice": 200, "gain": -87 },
    { "name": "Deepak Builders", "ipoPrice": 203, "listingPrice": 200, "gain": -1 },
    { "name": "Hyundai Motor India", "ipoPrice": 1960, "listingPrice": 1934, "gain": -1 },
    { "name": "Garuda Construction", "ipoPrice": 95, "listingPrice": 105, "gain": 10 },
    { "name": "Diffusion Engineers", "ipoPrice": 168, "listingPrice": 193, "gain": 15 },
    { "name": "KRN Heat Exchanger", "ipoPrice": 220, "listingPrice": 480, "gain": 118 },
    { "name": "Manba Finance", "ipoPrice": 120, "listingPrice": 150, "gain": 25 },
    { "name": "Northern Arc Capital", "ipoPrice": 263, "listingPrice": 351, "gain": 33 },
    { "name": "Arkade Developers", "ipoPrice": 128, "listingPrice": 176, "gain": 36 },
    { "name": "Western Carriers", "ipoPrice": 172, "listingPrice": 171, "gain": -1 },
    { "name": "P N Gadgil Jewellers", "ipoPrice": 480, "listingPrice": 840, "gain": 75 },
    { "name": "Bajaj Housing Finance", "ipoPrice": 70, "listingPrice": 150, "gain": 114 },
    { "name": "Kross", "ipoPrice": 240, "listingPrice": 240, "gain": 0 },
    { "name": "Tolins Tyres", "ipoPrice": 226, "listingPrice": 227, "gain": 0 },
    { "name": "Shree Tirupati Balajee", "ipoPrice": 83, "listingPrice": 90, "gain": 8 },
    { "name": "Gala Precision Engineering", "ipoPrice": 529, "listingPrice": 721, "gain": 36 },
    { "name": "Baazar Style Retail", "ipoPrice": 389, "listingPrice": 389, "gain": 0 },
    { "name": "Premier Energies", "ipoPrice": 450, "listingPrice": 990, "gain": 120 },
    { "name": "ECOS Mobility", "ipoPrice": 334, "listingPrice": 390, "gain": 17 },
    { "name": "Orient Technologies", "ipoPrice": 206, "listingPrice": 288, "gain": 40 },
    { "name": "Interarch Building Products", "ipoPrice": 900, "listingPrice": 1299, "gain": 44 },
    { "name": "Saraswati Saree", "ipoPrice": 160, "listingPrice": 194, "gain": 21 },
    { "name": "FirstCry", "ipoPrice": 465, "listingPrice": 651, "gain": 40 },
    { "name": "Unicommerce eSolutions", "ipoPrice": 108, "listingPrice": 235, "gain": 118 },
    { "name": "Ola Electric", "ipoPrice": 76, "listingPrice": 76, "gain": 0 },
    { "name": "Ceigall India", "ipoPrice": 401, "listingPrice": 419, "gain": 5 },
    { "name": "Akums Drugs", "ipoPrice": 679, "listingPrice": 725, "gain": 7 },
    { "name": "Sanstar", "ipoPrice": 95, "listingPrice": 109, "gain": 15 },
    { "name": "Emcure Pharmaceuticals", "ipoPrice": 1008, "listingPrice": 1325, "gain": 31 },
    { "name": "Bansal Wire", "ipoPrice": 256, "listingPrice": 356, "gain": 39 },
    { "name": "Vraj Iron and Steel", "ipoPrice": 207, "listingPrice": 240, "gain": 16 },
    { "name": "Allied Blenders and Distillers", "ipoPrice": 281, "listingPrice": 320, "gain": 13 },
    { "name": "Stanley Lifestyles", "ipoPrice": 369, "listingPrice": 499, "gain": 35 },
    { "name": "DEE Piping Systems", "ipoPrice": 203, "listingPrice": 339, "gain": 67 },
    { "name": "Akme Fintrade", "ipoPrice": 120, "listingPrice": 125, "gain": 6 },
    { "name": "Ixigo", "ipoPrice": 93, "listingPrice": 138, "gain": 48 },
    { "name": "Kronox Lab Sciences", "ipoPrice": 136, "listingPrice": 165, "gain": 21 },
    { "name": "Awfis Space", "ipoPrice": 383, "listingPrice": 435, "gain": 14 },
    { "name": "Go Digit Insurance", "ipoPrice": 272, "listingPrice": 281, "gain": 3 },
    { "name": "TBO TEK", "ipoPrice": 920, "listingPrice": 1426, "gain": 55 },
    { "name": "Aadhar Housing", "ipoPrice": 350, "listingPrice": 350, "gain": 0 },
    { "name": "Indegene", "ipoPrice": 415, "listingPrice": 655, "gain": 58 },
    { "name": "JNK India", "ipoPrice": 415, "listingPrice": 621, "gain": 0.50 },
    { "name": "Vodafone Idea", "ipoPrice": 11, "listingPrice": 11.80, "gain": 0.07 },
    { "name": "Bharti Hexacom", "ipoPrice": 570, "listingPrice": 755, "gain": 0.32 },
    { "name": "SRM Contractors", "ipoPrice": 210, "listingPrice": 215, "gain": 0.03 },
    { "name": "Krystal Integrated", "ipoPrice": 715, "listingPrice": 795, "gain": 0.11 },
    { "name": "Popular Vehicles", "ipoPrice": 295, "listingPrice": 289, "gain": -0.02 },
    { "name": "Gopal Snacks", "ipoPrice": 401, "listingPrice": 351, "gain": -0.13 },
    { "name": "JG Chemicals", "ipoPrice": 221, "listingPrice": 209, "gain": -0.05 },
    { "name": "R K SWAMY", "ipoPrice": 288, "listingPrice": 250, "gain": -0.13 },
    { "name": "Mukka Proteins", "ipoPrice": 28, "listingPrice": 44, "gain": 0.57 },
    { "name": "Exicom Tele-Systems", "ipoPrice": 142, "listingPrice": 265, "gain": 0.87 },
    { "name": "Platinum Industries", "ipoPrice": 171, "listingPrice": 225, "gain": 0.32 },
    { "name": "GPT Healthcare", "ipoPrice": 186, "listingPrice": 195, "gain": 0.05 },
    { "name": "Juniper Hotels", "ipoPrice": 360, "listingPrice": 361, "gain": 0.00 },
    { "name": "Vibhor Steel Tubes", "ipoPrice": 151, "listingPrice": 425, "gain": 1.81 },
    { "name": "Entero Healthcare Solutions", "ipoPrice": 1258, "listingPrice": 1245, "gain": -0.01 },
    { "name": "Rashi Peripherals", "ipoPrice": 311, "listingPrice": 339, "gain": 0.09 },
    { "name": "Capital Small Finance Bank", "ipoPrice": 468, "listingPrice": 430, "gain": -0.08 },
    { "name": "Jana Small Finance Bank", "ipoPrice": 414, "listingPrice": 396, "gain": -0.04 },
    { "name": "Apeejay Surrendra Park Hotels", "ipoPrice": 155, "listingPrice": 187, "gain": 0.21 },
    { "name": "BLS-E Services", "ipoPrice": 135, "listingPrice": 305, "gain": 1.26 },
    { "name": "Nova Agri Tech", "ipoPrice": 41, "listingPrice": 55, "gain": 0.34 },
    { "name": "EPACK Durable", "ipoPrice": 230, "listingPrice": 221, "gain": -0.04 },
    { "name": "Medi Assist Healthcare", "ipoPrice": 418, "listingPrice": 465, "gain": 0.11 },
    { "name": "Jyoti CNC Automation", "ipoPrice": 331, "listingPrice": 370, "gain": 0.12 }

],
"2023": [
    { "name": "Innova Captab", "ipoPrice": 448, "listingPrice": 456, "gain": 2 },
    { "name": "Azad Engineering", "ipoPrice": 524, "listingPrice": 706, "gain": 37 },
    { "name": "RBZ Jewellers", "ipoPrice": 100, "listingPrice": 100, "gain": 0 },
    { "name": "Happy Forgings", "ipoPrice": 850, "listingPrice": 1000, "gain": 18 },
    { "name": "Credo Brands (Mufti Jeans)", "ipoPrice": 280, "listingPrice": 282, "gain": 0 },
    { "name": "Motisons Jewellers", "ipoPrice": 55, "listingPrice": 109, "gain": 98 },
    { "name": "Suraj Estate Developers", "ipoPrice": 360, "listingPrice": 340, "gain": -6 },
    { "name": "Muthoot Microfin", "ipoPrice": 291, "listingPrice": 275, "gain": -5 },
    { "name": "Inox India", "ipoPrice": 660, "listingPrice": 934, "gain": 42 },
    { "name": "India Shelter Finance", "ipoPrice": 493, "listingPrice": 620, "gain": 25 },
    { "name": "DOMS IPO", "ipoPrice": 790, "listingPrice": 1399, "gain": 77 },
    { "name": "Flair Writing", "ipoPrice": 304, "listingPrice": 503, "gain": 65 },
    { "name": "Gandhar Oil", "ipoPrice": 169, "listingPrice": 298, "gain": 76 },
    { "name": "Fedbank Financial Services", "ipoPrice": 140, "listingPrice": 138, "gain": -1 },
    { "name": "Tata Technologies", "ipoPrice": 500, "listingPrice": 1200, "gain": 140 },
    { "name": "IREDA", "ipoPrice": 32, "listingPrice": 50, "gain": 56 },
    { "name": "ASK Automotive", "ipoPrice": 282, "listingPrice": 305, "gain": 8 },
    { "name": "Protean eGov Technologies", "ipoPrice": 792, "listingPrice": 792, "gain": 0 },
    { "name": "ESAF Small Finance Bank", "ipoPrice": 60, "listingPrice": 71, "gain": 18 },
    { "name": "Mamaearth", "ipoPrice": 324, "listingPrice": 330, "gain": 2 },
    { "name": "Cello World", "ipoPrice": 648, "listingPrice": 829, "gain": 28 },
    { "name": "Blue Jet Healthcare", "ipoPrice": 346, "listingPrice": 380, "gain": 10 },
    { "name": "IRM Energy", "ipoPrice": 505, "listingPrice": 477, "gain": -6 },
    { "name": "Plaza Wires", "ipoPrice": 54, "listingPrice": 76, "gain": 41 },
    { "name": "Valiant Laboratories", "ipoPrice": 140, "listingPrice": 162, "gain": 16 },
    { "name": "Updater Services", "ipoPrice": 300, "listingPrice": 285, "gain": -5 },
    { "name": "Manoj Vaibhav Gems", "ipoPrice": 215, "listingPrice": 215, "gain": 0 },
    { "name": "JSW Infrastructure", "ipoPrice": 119, "listingPrice": 143, "gain": 20 },
    { "name": "Yatra Online", "ipoPrice": 142, "listingPrice": 127, "gain": -10 },
    { "name": "Sai Silks Kalamandir", "ipoPrice": 222, "listingPrice": 231, "gain": 8 },
    { "name": "Signature Global", "ipoPrice": 385, "listingPrice": 444, "gain": 15 },
    { "name": "Zaggle Prepaid Ocean Services", "ipoPrice": 164, "listingPrice": 164, "gain": 0 },
    { "name": "Samhi Hotels", "ipoPrice": 126, "listingPrice": 134, "gain": 7 },
    { "name": "EMS IPO", "ipoPrice": 211, "listingPrice": 282, "gain": 34 },
    { "name": "RR Kabel", "ipoPrice": 1035, "listingPrice": 1180, "gain": 14 },
    { "name": "Jupiter Life Line Hospitals", "ipoPrice": 735, "listingPrice": 973, "gain": 32 },
    { "name": "Rishabh Instruments", "ipoPrice": 441, "listingPrice": 460, "gain": 4 },
    { "name": "Ratnaveer Precision Engineering", "ipoPrice": 98, "listingPrice": 128, "gain": 31 },
    { "name": "Vishnu Prakash R Punglia", "ipoPrice": 99, "listingPrice": 165, "gain": 67 },
    { "name": "Aeroflex Industries", "ipoPrice": 108, "listingPrice": 197, "gain": 83 },
    { "name": "Pyramid Technoplast", "ipoPrice": 166, "listingPrice": 187, "gain": 13 },
    { "name": "TVS Supply Chain Solutions", "ipoPrice": 197, "listingPrice": 207, "gain": 5 },
    { "name": "Concord Biotech", "ipoPrice": 741, "listingPrice": 900, "gain": 21 },
    { "name": "SBFC Finance", "ipoPrice": 57, "listingPrice": 82, "gain": 44 },
    { "name": "Yatharth Hospital", "ipoPrice": 300, "listingPrice": 306, "gain": 2 },
    { "name": "Netweb Technologies", "ipoPrice": 500, "listingPrice": 947, "gain": 89 },
    { "name": "Utkarsh Small Finance Bank", "ipoPrice": 25, "listingPrice": 40, "gain": 60 },
    { "name": "Senco Gold", "ipoPrice": 317, "listingPrice": 430, "gain": 36 },
    { "name": "Cyient DLM", "ipoPrice": 265, "listingPrice": 403, "gain": 52 },
    { "name": "IdeaForge", "ipoPrice": 672, "listingPrice": 1300, "gain": 94 },
    { "name": "HMA Agro", "ipoPrice": 585, "listingPrice": 615, "gain": 5 },
    { "name": "IKIO Lighting", "ipoPrice": 285, "listingPrice": 391, "gain": 38 },
    { "name": "Nexus Select Trust", "ipoPrice": 100, "listingPrice": 103, "gain": 3 },
    { "name": "Mankind Pharma", "ipoPrice": 1080, "listingPrice": 1300, "gain": 20 },
    { "name": "Avalon Technologies", "ipoPrice": 436, "listingPrice": 436, "gain": 0 },
    { "name": "Udayshivakumar Infra", "ipoPrice": 35, "listingPrice": 30, "gain": -14 },
    { "name": "Global Surfaces", "ipoPrice": 140, "listingPrice": 164, "gain": 16 },
    { "name": "Divgi TorqTransfer Systems", "ipoPrice": 590, "listingPrice": 620, "gain": 5 }
],
"2022": [
    { "name": "Sah Polymers", "ipoPrice": 99, "listingPrice": 85, "gain": -0.14 },
    { "name": "Radiant Cash Management", "ipoPrice": 99, "listingPrice": 103, "gain": 0.04 },
    { "name": "Elin Electronics", "ipoPrice": 247, "listingPrice": 244, "gain": 0.00 },
    { "name": "KFin Technologies", "ipoPrice": 366, "listingPrice": 367, "gain": 0.00 },
    { "name": "Abans Holdings", "ipoPrice": 270, "listingPrice": 273, "gain": 0.01 },
    { "name": "Landmark Cars", "ipoPrice": 506, "listingPrice": 471, "gain": -0.07 },
    { "name": "Sula Vineyards", "ipoPrice": 357, "listingPrice": 361, "gain": 0.01 },
    { "name": "Uniparts India", "ipoPrice": 577, "listingPrice": 575, "gain": -0.02 },
    { "name": "Dharmaj Crop Guard", "ipoPrice": 237, "listingPrice": 266, "gain": 0.12 },
    { "name": "Keystone Realtors", "ipoPrice": 541, "listingPrice": 555, "gain": 0.03 },
    { "name": "Inox Green Energy", "ipoPrice": 65, "listingPrice": 60, "gain": -0.08 },
    { "name": "Kaynes Technology", "ipoPrice": 587, "listingPrice": 778, "gain": 0.33 },
    { "name": "Five Star Business Finance", "ipoPrice": 474, "listingPrice": 468, "gain": -0.01 },
    { "name": "Archean Chemical", "ipoPrice": 407, "listingPrice": 450, "gain": 0.11 },
    { "name": "Global Health", "ipoPrice": 330, "listingPrice": 401, "gain": 0.19 },
    { "name": "Bikaji Foods", "ipoPrice": 300, "listingPrice": 322, "gain": 0.08 },
    { "name": "DCX Systems", "ipoPrice": 207, "listingPrice": 287, "gain": 0.39 },
    { "name": "Tracxn", "ipoPrice": 80, "listingPrice": 84.5, "gain": 0.05 },
    { "name": "Electronics Mart", "ipoPrice": 59, "listingPrice": 90, "gain": 0.53 },
        { "name": "Harsha Engineers", "ipoPrice": 330, "listingPrice": 450, "gain": 0.36 },
        { "name": "Tamilnad Mercantile Bank", "ipoPrice": 510, "listingPrice": 495, "gain": -0.03 },
        { "name": "Dreamfolks Services", "ipoPrice": 326, "listingPrice": 508, "gain": 0.56 },
        { "name": "Syrma SGS", "ipoPrice": 220, "listingPrice": 260, "gain": 0.18 },
        { "name": "Aether Industries", "ipoPrice": 642, "listingPrice": 704, "gain": 0.10 },
        { "name": "eMudhra", "ipoPrice": 256, "listingPrice": 270, "gain": 0.05 },
        { "name": "Ethos", "ipoPrice": 878, "listingPrice": 825, "gain": -0.06 },
        { "name": "Paradeep Phosphates", "ipoPrice": 42, "listingPrice": 44, "gain": 0.05 },
        { "name": "Venus Pipes", "ipoPrice": 326, "listingPrice": 337, "gain": 0.04 },
        { "name": "Sah Polymers", "ipoPrice": 99, "listingPrice": 85, "gain": -0.14 },
        { "name": "Radiant Cash Management", "ipoPrice": 99, "listingPrice": 103, "gain": 0.04 },
        { "name": "Elin Electronics", "ipoPrice": 247, "listingPrice": 244, "gain": 0.00 },
        { "name": "KFin Technologies", "ipoPrice": 366, "listingPrice": 367, "gain": 0.00 },
        { "name": "Abans Holdings", "ipoPrice": 270, "listingPrice": 273, "gain": 0.01 },
        { "name": "Landmark Cars", "ipoPrice": 506, "listingPrice": 471, "gain": -0.07 },
        { "name": "Sula Vineyards", "ipoPrice": 357, "listingPrice": 361, "gain": 0.01 },
        { "name": "Uniparts India", "ipoPrice": 577, "listingPrice": 575, "gain": -0.02 },
        { "name": "Dharmaj Crop Guard", "ipoPrice": 237, "listingPrice": 266, "gain": 0.12 },
        { "name": "Keystone Realtors", "ipoPrice": 541, "listingPrice": 555, "gain": 0.03 },
        { "name": "Inox Green Energy", "ipoPrice": 65, "listingPrice": 60, "gain": -0.08 },
        { "name": "Kaynes Technology", "ipoPrice": 587, "listingPrice": 778, "gain": 0.33 },
        { "name": "Five Star Business Finance", "ipoPrice": 474, "listingPrice": 468, "gain": -0.01 },
        { "name": "Archean Chemical", "ipoPrice": 407, "listingPrice": 450, "gain": 0.11 },
    

            { "name": "Global Health", "ipoPrice": 330, "listingPrice": 401, "gain": 0.19 },
            { "name": "Bikaji Foods", "ipoPrice": 300, "listingPrice": 322, "gain": 0.08 },
            { "name": "DCX Systems", "ipoPrice": 207, "listingPrice": 287, "gain": 0.39 },
            { "name": "Tracxn", "ipoPrice": 80, "listingPrice": 84.5, "gain": 0.05 },
            { "name": "Electronics Mart", "ipoPrice": 59, "listingPrice": 90, "gain": 0.53 },
            { "name": "Harsha Engineers", "ipoPrice": 330, "listingPrice": 450, "gain": 0.36 },
            { "name": "Tamilnad Mercantile Bank", "ipoPrice": 510, "listingPrice": 495, "gain": -0.03 },
            { "name": "Dreamfolks Services", "ipoPrice": 326, "listingPrice": 508, "gain": 0.56 },
            { "name": "Syrma SGS", "ipoPrice": 220, "listingPrice": 260, "gain": 0.18 },
            { "name": "Aether Industries", "ipoPrice": 642, "listingPrice": 704, "gain": 0.10 },
            { "name": "eMudhra", "ipoPrice": 256, "listingPrice": 270, "gain": 0.05 },
            { "name": "Ethos", "ipoPrice": 878, "listingPrice": 825, "gain": -0.06 },
            { "name": "Paradeep Phosphates", "ipoPrice": 42, "listingPrice": 44, "gain": 0.05 },
            { "name": "Venus Pipes", "ipoPrice": 326, "listingPrice": 337, "gain": 0.04 },
            { "name": "Paytm", "ipoPrice": 2150, "listingPrice": 1950, "gain": -0.09 },
            { "name": "Policybazaar", "ipoPrice": 980, "listingPrice": 1150, "gain": 0.20 },
            { "name": "Sigachi Industries", "ipoPrice": 163, "listingPrice": 570, "gain": 2.50 },
            { "name": "SJS Enterprises", "ipoPrice": 542, "listingPrice": 542, "gain": 0.00 },
            { "name": "Fino Payments Bank", "ipoPrice": 577, "listingPrice": 543, "gain": -0.06 },
            { "name": "Nykaa", "ipoPrice": 1125, "listingPrice": 2018, "gain": 0.79 },
            { "name": "Aditya Birla AMC", "ipoPrice": 712, "listingPrice": 712, "gain": 0.00 },
            { "name": "Paras Defence", "ipoPrice": 175, "listingPrice": 469, "gain": 1.70 },
            { "name": "Sansera Engineering", "ipoPrice": 744, "listingPrice": 811, "gain": 0.09 },
            { "name": "Vijaya Diagnostic", "ipoPrice": 531, "listingPrice": 540, "gain": 0.02 },
            { "name": "Ami Organics", "ipoPrice": 610, "listingPrice": 910, "gain": 0.49 },
            { "name": "Chemplast Sanmar", "ipoPrice": 541, "listingPrice": 550, "gain": 0.02 },
            { "name": "Aptus Value", "ipoPrice": 353, "listingPrice": 333, "gain": -0.06 },
        

                { "name": "Nuvoco Vistas", "ipoPrice": 570, "listingPrice": 485, "gain": -0.17 },
                { "name": "CarTrade Tech", "ipoPrice": 1618, "listingPrice": 1505, "gain": -0.01 },
                { "name": "Windlas Biotech", "ipoPrice": 460, "listingPrice": 437, "gain": -0.05 },
                { "name": "Devyani International", "ipoPrice": 90, "listingPrice": 141, "gain": 0.57 },
                { "name": "Exxaro Tiles", "ipoPrice": 120, "listingPrice": 126, "gain": 0.01 },
                { "name": "Krsnaa Diagnostics", "ipoPrice": 954, "listingPrice": 1005, "gain": 0.05 },
                { "name": "Rolex Rings", "ipoPrice": 900, "listingPrice": 1250, "gain": 0.38 },
                { "name": "Glenmark Life Sciences", "ipoPrice": 720, "listingPrice": 750, "gain": 0.04 },
                { "name": "Tatva Chintan", "ipoPrice": 1083, "listingPrice": 2111, "gain": 0.95 },
                { "name": "Zomato", "ipoPrice": 76, "listingPrice": 126, "gain": 0.53 },
                { "name": "GR Infra", "ipoPrice": 837, "listingPrice": 1716, "gain": 1.05 },
                { "name": "Clean Science", "ipoPrice": 900, "listingPrice": 1784, "gain": 0.98 },
                { "name": "India Pesticides", "ipoPrice": 296, "listingPrice": 350, "gain": 0.22 },
                { "name": "Dodla Dairy", "ipoPrice": 428, "listingPrice": 550, "gain": 0.28 },
                { "name": "KIMS Hospital", "ipoPrice": 825, "listingPrice": 1009, "gain": 0.22 },
                { "name": "Shyam Metalics", "ipoPrice": 306, "listingPrice": 380, "gain": 0.24 },
                { "name": "Sona BLW Precision", "ipoPrice": 291, "listingPrice": 301, "gain": 0.03 },
                { "name": "Lodha Developers", "ipoPrice": 486, "listingPrice": 436, "gain": -0.10 },
                { "name": "Barbeque Nation", "ipoPrice": 500, "listingPrice": 482, "gain": -0.02 },
                { "name": "Nazara Tech", "ipoPrice": 1101, "listingPrice": 1990, "gain": 0.81 },
                { "name": "Suryoday Bank", "ipoPrice": 305, "listingPrice": 292, "gain": -0.04 },
                { "name": "Kalyan Jewellers", "ipoPrice": 87, "listingPrice": 73.95, "gain": -0.15 },
                { "name": "Laxmi Organic", "ipoPrice": 130, "listingPrice": 155.50, "gain": 0.20 },
                { "name": "Craftsman Automation", "ipoPrice": 1490, "listingPrice": 1359, "gain": -0.09 },
                { "name": "Anupam Rasayan", "ipoPrice": 555, "listingPrice": 520, "gain": -0.06 },
                { "name": "EaseMyTrip", "ipoPrice": 187, "listingPrice": 212.25, "gain": 0.14 },
                { "name": "MTAR Technologies", "ipoPrice": 575, "listingPrice": 1050, "gain": 0.83 },
                { "name": "Heranba Industries", "ipoPrice": 627, "listingPrice": 900, "gain": 0.44 },
                { "name": "RailTel", "ipoPrice": 94, "listingPrice": 109, "gain": 0.16 }
                        
]


}


export default closedipoData;